// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXyM8at7_wvo-2qcfxex8nrZ1D5DjAsag',
    appId: '1:400812090135:web:62afcbf736078321e00d52',
    messagingSenderId: '400812090135',
    projectId: 'fl-database2026',
    authDomain: 'fl-database2026.firebaseapp.com',
    storageBucket: 'fl-database2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqRlvLhC-jTb352sUKolnHH0SeL_QOooI',
    appId: '1:400812090135:android:81ca92de76e81bd7e00d52',
    messagingSenderId: '400812090135',
    projectId: 'fl-database2026',
    storageBucket: 'fl-database2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEdtvO60UL3GWbShzhchOCXyu8FY0VQc0',
    appId: '1:400812090135:ios:f9efa7b6925adb95e00d52',
    messagingSenderId: '400812090135',
    projectId: 'fl-database2026',
    storageBucket: 'fl-database2026.firebasestorage.app',
    iosBundleId: 'com.example.flutterCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEdtvO60UL3GWbShzhchOCXyu8FY0VQc0',
    appId: '1:400812090135:ios:f9efa7b6925adb95e00d52',
    messagingSenderId: '400812090135',
    projectId: 'fl-database2026',
    storageBucket: 'fl-database2026.firebasestorage.app',
    iosBundleId: 'com.example.flutterCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXyM8at7_wvo-2qcfxex8nrZ1D5DjAsag',
    appId: '1:400812090135:web:e1a10e0c6de84554e00d52',
    messagingSenderId: '400812090135',
    projectId: 'fl-database2026',
    authDomain: 'fl-database2026.firebaseapp.com',
    storageBucket: 'fl-database2026.firebasestorage.app',
  );

}